#!/bin/sh
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
output_dir=${TMPDIR:-/tmp}/xiebiao-hugo-test
cache_dir=${TMPDIR:-/tmp}/xiebiao-hugo-cache
production_output_dir=${TMPDIR:-/tmp}/xiebiao-hugo-production-test

hugo --source "$project_dir" --config hugo.toml,tests/hugo/hugo.toml --destination "$output_dir" --cacheDir "$cache_dir" --cleanDestinationDir

english_homepage="$output_dir/index.html"
error_page="$output_dir/404.html"
english_post_index="$output_dir/posts/index.html"
english_figure="$output_dir/posts/figure-shortcode-test/index.html"
chinese_homepage="$output_dir/zh/index.html"
chinese_post_index="$output_dir/zh/posts/index.html"
chinese_figure="$output_dir/zh/posts/figure-shortcode-test/index.html"
chinese_only="$output_dir/zh/posts/chinese-only/index.html"
chinese_photo_index="$output_dir/zh/photos/index.html"
english_project_index="$output_dir/projects/index.html"
english_project_detail="$output_dir/projects/sample-project/index.html"
chinese_project_detail="$output_dir/zh/projects/sample-project/index.html"
english_photo_index="$output_dir/photos/index.html"
english_photo_detail="$output_dir/photos/sample-gallery/index.html"
chinese_photo_detail="$output_dir/zh/photos/sample-gallery/index.html"
english_older_photo_detail="$output_dir/photos/older-gallery/index.html"
chinese_older_photo_detail="$output_dir/zh/photos/older-gallery/index.html"
robots_file="$output_dir/robots.txt"

test -f "$english_homepage"
test -f "$error_page"
test -f "$english_post_index"
test -f "$english_figure"
test -f "$chinese_homepage"
test -f "$chinese_post_index"
test -f "$chinese_figure"
test -f "$chinese_only"
test -f "$chinese_photo_index"
test -f "$english_project_detail"
test -f "$english_photo_detail"
test -f "$english_project_index"
test -f "$chinese_project_detail"
test -f "$english_photo_index"
test -f "$chinese_photo_detail"
test -f "$english_older_photo_detail"
test -f "$chinese_older_photo_detail"
test -f "$robots_file"
grep -q '^User-agent: OAI-SearchBot$' "$robots_file"
grep -q '^User-agent: GPTBot$' "$robots_file"
grep -q '^User-agent: Claude-SearchBot$' "$robots_file"
grep -q '^User-agent: ClaudeBot$' "$robots_file"
grep -q '^Sitemap: https://xiebiao.com/sitemap.xml$' "$robots_file"
grep -q 'class="site-header"' "$english_homepage"
grep -q 'class="error-page"' "$error_page"
grep -q '<h1 id="error-heading">404</h1>' "$error_page"
grep -q '<p class="error-subtitle" lang="en">Not Found</p>' "$error_page"
grep -q '测试页面不存在。' "$error_page"
grep -q 'The test page could not be found.' "$error_page"
grep -q 'name="robots" content="noindex"' "$error_page"
grep -q 'href="/zh/"' "$error_page"
grep -q 'class="error-message" lang="en-US"' "$error_page"
grep -A8 '\.error-page {' "$output_dir/style.css" | grep -q "font-family: 'LXGW WenKai'"
grep -A8 '\.error-message {' "$output_dir/style.css" | grep -q 'line-break: strict'
grep -A8 '\.error-message {' "$output_dir/style.css" | grep -q 'text-align: center'
grep -q "font-family: 'ET Book'" "$output_dir/style.css"
grep -q 'cdnjs.cloudflare.com/ajax/libs/tufte-css/1.8.0/et-book/et-book-roman-line-figures' "$output_dir/style.css"
grep -q "url('/fonts/et-book/et-book-roman.woff')" "$output_dir/style.css"
grep -q 'html\[lang\^="en"\] \.article-body' "$output_dir/style.css"
test -f "$output_dir/fonts/et-book/et-book-roman.woff"
test -f "$output_dir/fonts/et-book/et-book-italic.woff"
test -f "$output_dir/fonts/et-book/et-book-bold.woff"
test -f "$output_dir/fonts/et-book/LICENSE"
test ! -e "$output_dir/404/index.html"
grep -q 'class="site-header"' "$english_post_index"
grep -q 'class="site-header"' "$english_figure"
grep -q 'class="language-toggle"' "$english_post_index"
grep -q 'href="/zh/posts/"' "$english_homepage"
grep -q 'href="/zh/posts/"' "$chinese_homepage"
grep -q 'href="/projects/"' "$english_homepage"
grep -q 'href="/zh/photos/"' "$english_homepage"
grep -q 'href="/zh/photos/"' "$chinese_homepage"
grep -q 'class="home-landing"' "$english_homepage"
grep -q 'class="home-card"' "$english_homepage"
grep -A5 '\.home-card {' "$output_dir/style.css" | grep -q 'justify-content: center'
grep -q 'class="home-social-icons home-social-inline"' "$english_homepage"
grep -q 'href="https://www\.threads\.com/@pushbeat\.app"' "$english_homepage"
grep -q 'aria-label="Threads"' "$english_homepage"
for page in "$english_homepage" "$chinese_homepage" "$error_page" "$english_post_index" "$english_figure" "$english_project_index" "$english_project_detail" "$english_photo_index" "$english_photo_detail"; do
  grep -q 'class="site-footer"' "$page"
  grep -q '&copy; [0-9][0-9][0-9][0-9] www\.xiebiao\.com' "$page"
done
grep -q '<html lang="en-US">' "$english_homepage"
grep -q '<title>Bill Xie · Independent Software Engineer</title>' "$english_homepage"
grep -q 'name="description" content="Bill Xie is an independent software engineer in China building thoughtful products for himself, his daughter, for fun, and for a living\."' "$english_homepage"
grep -q 'property="og:title" content="Bill Xie · Independent Software Engineer"' "$english_homepage"
grep -q 'name="twitter:title" content="Bill Xie · Independent Software Engineer"' "$english_homepage"
grep -q 'name="robots" content="max-image-preview:large,max-snippet:-1,max-video-preview:-1"' "$english_homepage"
grep -q 'href="/zh/" hreflang="zh"' "$english_homepage"
grep -q 'rel="alternate" hreflang="x-default" href="https://xiebiao.com/"' "$english_homepage"
grep -q 'rel="alternate" type="application/rss+xml"' "$english_homepage"
grep -q '"@type":"ProfilePage"' "$english_homepage"
grep -q '"@type":"WebSite"' "$english_homepage"
grep -q '"description":"Independent software engineer in China building thoughtful products for himself, his daughter, for fun, and for a living\."' "$english_homepage"
grep -q '"jobTitle":"Independent Software Engineer"' "$english_homepage"
grep -q '"knowsAbout":\["Independent software development","Product design","Writing","Photography"\]' "$english_homepage"
grep -q '"about":{"@id":"https://xiebiao.com/#person"}' "$english_homepage"
grep -q '<html lang="zh-CN">' "$chinese_homepage"
grep -q '<title>于川海 · 独立软件工程师</title>' "$chinese_homepage"
grep -q 'name="description" content="于川海（Bill Xie）是一名生活在中国的独立软件工程师，分享独立产品、写作与摄影作品。"' "$chinese_homepage"
grep -q '"jobTitle":"独立软件工程师"' "$chinese_homepage"
grep -q 'href="/" hreflang="en"' "$chinese_homepage"
grep -q 'name="description" content="中文文章的独立搜索摘要。"' "$chinese_only"
grep -q '"@type":"BlogPosting"' "$chinese_only"
grep -q '"headline":"仅中文文章"' "$chinese_only"
grep -q 'property="og:url" content="https://xiebiao.com/zh/posts/chinese-only/"' "$chinese_only"
grep -q '<loc>https://xiebiao.com/zh/posts/chinese-only/</loc>' "$output_dir/zh/sitemap.xml"
! grep -R -q '<loc>http://xiebiao\.com/' "$output_dir"/*/sitemap.xml "$output_dir/sitemap.xml"
grep -q 'href="/posts/figure-shortcode-test/" hreflang="en"' "$chinese_figure"
grep -q 'href="/zh/posts/figure-shortcode-test/" hreflang="zh"' "$english_figure"
grep -q 'href="/posts/" hreflang="en"' "$chinese_only"
grep -q 'class="article-page latest-post"' "$english_post_index"
grep -q '>Figure shortcode test<' "$english_post_index"
! grep -q 'post-sidebar-taxonomy-only' "$english_post_index"
grep -q 'class="post-taxonomy-disclosure"' "$english_post_index"
grep -q '>Categories &amp; tags<' "$english_post_index"
grep -q '>分类与标签<' "$chinese_post_index"
! grep -q 'post-taxonomy-disclosure' "$english_figure"
! grep -q 'post-sidebar-taxonomy-only' "$english_figure"
grep -q 'class="post-navigation" aria-label="文章导航"' "$chinese_post_index"
grep -q 'class="post-navigation" aria-label="文章导航"' "$chinese_figure"
grep -q 'class="post-navigation-label">← 较新一篇' "$chinese_figure"
grep -q 'href="/zh/posts/chinese-only/"' "$chinese_figure"
grep -q 'class="project-index-topbar posts-content-topbar"' "$english_post_index"
grep -q '\.post-taxonomy-disclosure summary::after' "$output_dir/style.css"
grep -A5 '\.post-taxonomy-disclosure-panel {' "$output_dir/style.css" | grep -q 'text-align: left'
grep -q '\.post-navigation-older {' "$output_dir/style.css"
grep -A4 '\.post-navigation-newer,' "$output_dir/style.css" | grep -q 'grid-column: 1'
grep -q '>Categories<' "$english_post_index"
grep -q 'href="/categories/photography/"' "$english_post_index"
grep -q '>Tags<' "$english_post_index"
! grep -q '>Content<' "$english_post_index"
grep -q 'August 29, 2026' "$english_figure"
grep -q '2026年8月29日' "$chinese_figure"
grep -q "I’m an indie software engineer—not a vibe coder\. I like keeping things real and staying open to new ideas\." "$english_homepage"
! grep -q 'home-building-lines' "$english_homepage"
grep -q '>Building for myself\.<' "$english_homepage"
grep -q 'Building for my daughter\.<br>' "$english_homepage"
grep -q 'Building for fun\.<br>' "$english_homepage"
grep -q 'Building for money\.</span>' "$english_homepage"
! grep -q 'Building for myself' "$chinese_homepage"
! grep -q 'data-i18n\|localStorage\|pageTranslations' "$english_homepage"
grep -q 'class="project-card-grid"' "$english_project_index"
grep -q 'class="project-index-topbar"' "$english_project_index"
grep -q 'class="project-card-link"' "$english_project_index"
grep -q 'class="project-detail-header"' "$english_project_detail"
grep -q '"@type":"SoftwareApplication"' "$english_project_detail"
grep -q '"name":"Sample project"' "$english_project_detail"
grep -q 'class="project-link" href="/zh/posts/"' "$english_project_detail"
grep -q 'class="project-link" href="/zh/photos/"' "$english_project_detail"
grep -q 'href="/projects/sample-project/" hreflang="en"' "$chinese_project_detail"
grep -q 'In development' "$english_project_detail"
grep -q 'class="latest-photo-story"' "$english_photo_index"
grep -q 'class="photo-story-gallery"' "$english_photo_index"
grep -q 'sizes="(max-width: 760px) calc(100vw - 2rem), 760px"' "$chinese_photo_index"
grep -q 'src="https://media.example/cdn-cgi/image/width=960' "$chinese_photo_index"
! grep -q 'width=1200' "$chinese_photo_index"
grep -q 'class="photo-story-gallery"' "$english_photo_detail"
grep -q 'class="photo-story photo-single-page"' "$english_photo_detail"
grep -q 'fetchpriority="high"' "$english_photo_detail"
grep -q '"@type":"ImageObject"' "$english_photo_detail"
grep -q '"contentLocation":{"@type":"Place","name":"Qinghai"}' "$english_photo_detail"
grep -q 'property="og:image:alt" content="Sample photo"' "$english_photo_detail"
grep -q 'class="photo-single-topbar"' "$english_photo_detail"
grep -q 'class="post-navigation photo-navigation" aria-label="Photo story navigation"' "$english_photo_detail"
grep -q 'class="post-navigation-label">Older post →' "$english_photo_detail"
grep -q 'href="/photos/older-gallery/"' "$english_photo_detail"
grep -q 'class="post-navigation-label">← Newer post' "$english_older_photo_detail"
grep -q 'href="/photos/sample-gallery/"' "$english_older_photo_detail"
! grep -q 'class="photo-random-link"' "$english_photo_detail"
! grep -q 'data-photo-destinations' "$english_photo_detail"
! grep -q 'photo-random.js' "$english_photo_detail"
grep -q 'data-photo-destinations' "$english_photo_index"
grep -q 'sizes="(max-width: 760px) calc(100vw - 2rem), 760px"' "$english_photo_detail"
grep -q '\.photo-single-page \.photo-story-gallery' "$output_dir/style.css"
grep -q '\.photo-latest-page \.photo-story-gallery' "$output_dir/style.css"
grep -A4 '\.photo-story-intro {' "$output_dir/style.css" | grep -q 'font-size: inherit'
grep -q 'property="og:image" content="https://xiebiao.com/images/photo-960w.jpg"' "$english_photo_detail"
grep -q 'srcset="/images/photo-480w.jpg 480w, /images/photo-960w.jpg 960w"' "$english_photo_detail"
grep -q '<span class="photo-story-location">Qinghai</span>' "$english_photo_index"
grep -q '<span class="photo-story-location">Qinghai</span>' "$english_photo_detail"
grep -q '<time class="photo-story-date" datetime="2026-08-30">August 30, 2026</time>' "$english_photo_detail"
grep -q 'class="post-navigation photo-navigation" aria-label="影集导航"' "$chinese_photo_detail"
! grep -q 'Sample caption' "$english_photo_detail"
grep -q 'format=auto' "$english_figure"
grep -q 'width=960' "$english_figure"
grep -q 'alt="青海的田野"' "$english_figure"
grep -q '夏末，冷湖' "$english_figure"

hugo --source "$project_dir" --destination "$production_output_dir" --cacheDir "$cache_dir" --cleanDestinationDir

grep -q 'content="0; url=/zh/posts/"' "$production_output_dir/posts/index.html"
grep -q 'rel="canonical" href="https://xiebiao.com/zh/posts/"' "$production_output_dir/posts/index.html"
grep -q 'content="0; url=/zh/photos/"' "$production_output_dir/photos/index.html"
grep -q 'rel="canonical" href="https://xiebiao.com/zh/photos/"' "$production_output_dir/photos/index.html"
test ! -e "$production_output_dir/categories/index.html"
test ! -e "$production_output_dir/tags/index.html"
grep -q '<title>青海，冷湖 · 于川海</title>' "$production_output_dir/zh/photos/qinghai-lenghu/index.html"
grep -q '<title>新疆，昭苏 · 于川海</title>' "$production_output_dir/zh/photos/xinjiang-autumn-fields/index.html"
! grep -R -q '<title> · ' "$production_output_dir"
! grep -R -q '<h1></h1>' "$production_output_dir"
! grep -R -q 'class="language-toggle" href=""' "$production_output_dir"
! grep -q '<loc>https://xiebiao.com/posts/</loc>' "$production_output_dir/en/sitemap.xml"
! grep -q '<loc>https://xiebiao.com/photos/</loc>' "$production_output_dir/en/sitemap.xml"
