#!/bin/sh
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
output_dir=${TMPDIR:-/tmp}/xiebiao-hugo-test
cache_dir=${TMPDIR:-/tmp}/xiebiao-hugo-cache

hugo --source "$project_dir" --config hugo.toml,tests/hugo/hugo.toml --destination "$output_dir" --cacheDir "$cache_dir" --cleanDestinationDir

english_homepage="$output_dir/index.html"
english_post_index="$output_dir/posts/index.html"
english_figure="$output_dir/posts/figure-shortcode-test/index.html"
chinese_homepage="$output_dir/zh/index.html"
chinese_post_index="$output_dir/zh/posts/index.html"
chinese_figure="$output_dir/zh/posts/figure-shortcode-test/index.html"
chinese_only="$output_dir/zh/posts/chinese-only/index.html"
english_project_index="$output_dir/projects/index.html"
english_project_detail="$output_dir/projects/sample-project/index.html"
chinese_project_detail="$output_dir/zh/projects/sample-project/index.html"
english_photo_index="$output_dir/photos/index.html"
english_photo_detail="$output_dir/photos/sample-gallery/index.html"
chinese_photo_detail="$output_dir/zh/photos/sample-gallery/index.html"

test -f "$english_homepage"
test -f "$english_post_index"
test -f "$english_figure"
test -f "$chinese_homepage"
test -f "$chinese_post_index"
test -f "$chinese_figure"
test -f "$chinese_only"
test -f "$english_project_detail"
test -f "$english_photo_detail"
test -f "$english_project_index"
test -f "$chinese_project_detail"
test -f "$english_photo_index"
test -f "$chinese_photo_detail"
grep -q 'class="site-header"' "$english_homepage"
grep -q 'class="site-header"' "$english_post_index"
grep -q 'class="site-header"' "$english_figure"
grep -q 'class="language-toggle"' "$english_post_index"
grep -q 'href="/zh/posts/"' "$english_homepage"
grep -q 'href="/zh/posts/"' "$chinese_homepage"
grep -q 'href="/projects/"' "$english_homepage"
grep -q 'href="/zh/photos/"' "$english_homepage"
grep -q 'href="/zh/photos/"' "$chinese_homepage"
grep -q 'class="home-landing"' "$english_homepage"
grep -q 'class="home-card"' "$english_homepage"
grep -q 'class="home-social-icons home-social-inline"' "$english_homepage"
grep -q 'href="https://www\.threads\.com/@pushbeat\.app"' "$english_homepage"
grep -q 'aria-label="Threads"' "$english_homepage"
for page in "$english_homepage" "$chinese_homepage" "$english_post_index" "$english_figure" "$english_project_index" "$english_project_detail" "$english_photo_index" "$english_photo_detail"; do
  grep -q 'class="site-footer"' "$page"
  grep -q '&copy; [0-9][0-9][0-9][0-9] www\.xiebiao\.com' "$page"
done
grep -q '<html lang="en-US">' "$english_homepage"
grep -q 'href="/zh/" hreflang="zh"' "$english_homepage"
grep -q '<html lang="zh-CN">' "$chinese_homepage"
grep -q 'href="/" hreflang="en"' "$chinese_homepage"
grep -q 'href="/posts/figure-shortcode-test/" hreflang="en"' "$chinese_figure"
grep -q 'href="/zh/posts/figure-shortcode-test/" hreflang="zh"' "$english_figure"
grep -q 'href="/posts/" hreflang="en"' "$chinese_only"
grep -q 'class="article-page latest-post"' "$english_post_index"
grep -q '>Figure shortcode test<' "$english_post_index"
grep -q 'class="profile post-sidebar post-sidebar-taxonomy-only"' "$english_post_index"
grep -q 'class="project-index-topbar posts-content-topbar"' "$english_post_index"
grep -A3 '\.post-taxonomies {' "$output_dir/style.css" | grep -q 'text-align: right'
grep -A4 '\.post-tag-list {' "$output_dir/style.css" | grep -q 'justify-content: flex-end'
grep -q '>Categories<' "$english_post_index"
grep -q 'href="/categories/photography/"' "$english_post_index"
grep -q '>Tags<' "$english_post_index"
! grep -q '>Content<' "$english_post_index"
grep -q 'August 29, 2026' "$english_figure"
grep -q '2026年8月29日' "$chinese_figure"
grep -q "an indie software engineer, and I live in China\." "$english_homepage"
! grep -q 'data-i18n\|localStorage\|pageTranslations' "$english_homepage"
grep -q 'class="project-card-grid"' "$english_project_index"
grep -q 'class="project-index-topbar"' "$english_project_index"
grep -q 'class="project-card-link"' "$english_project_index"
grep -q 'class="project-detail-header"' "$english_project_detail"
grep -q 'class="project-link" href="/zh/posts/"' "$english_project_detail"
grep -q 'class="project-link" href="/zh/photos/"' "$english_project_detail"
grep -q 'href="/projects/sample-project/" hreflang="en"' "$chinese_project_detail"
grep -q 'In development' "$english_project_detail"
grep -q 'class="latest-photo-story"' "$english_photo_index"
grep -q 'class="photo-story-gallery"' "$english_photo_index"
grep -q 'class="photo-story-gallery"' "$english_photo_detail"
grep -q 'class="photo-story photo-single-page"' "$english_photo_detail"
grep -q 'sizes="(max-width: 760px) calc(100vw - 2rem), 960px"' "$english_photo_detail"
grep -q '\.photo-single-page \.photo-story-gallery' "$output_dir/style.css"
grep -A4 '\.photo-story-intro {' "$output_dir/style.css" | grep -q 'font-size: 1.125rem'
grep -q 'property="og:image" content="https://xiebiao.com/images/photo-960w.jpg"' "$english_photo_detail"
grep -q 'srcset="/images/photo-480w.jpg 480w, /images/photo-960w.jpg 960w"' "$english_photo_detail"
grep -q '<span class="photo-story-location">Qinghai</span>' "$english_photo_index"
grep -q '<span class="photo-story-location">Qinghai</span>' "$english_photo_detail"
grep -q '<time class="photo-story-date" datetime="2026-08-30">August 30, 2026</time>' "$english_photo_detail"
! grep -q 'Sample caption' "$english_photo_detail"
grep -q 'format=auto' "$english_figure"
grep -q 'width=960' "$english_figure"
grep -q 'alt="青海的田野"' "$english_figure"
grep -q '夏末，冷湖' "$english_figure"
